"""
Research stage: one agent with a tool loop.

  * At least `research.min_iterations` and at most `research.max_iterations` tool rounds.
  * Tools are bound to a lookback window that ends at the cutoff date.
  * The agent must NOT forecast; it writes a fixed-template report.
  * Every claim cites a numbered source [n]; numbering is assigned by code, and the
    "## Sources" list is generated by code from the sources actually cited.
  * Thinking tags / tool-call residue are stripped from the final report.
"""
from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field

from advanced_bot import llm
from advanced_bot.config import Config
from advanced_bot.llm import RunContext
from advanced_bot.question_view import QuestionView
from advanced_bot.tools import SourceItem, TimeWindow, available_tools, run_tool, tool_schemas

logger = logging.getLogger(__name__)

REPORT_SECTIONS = [
    "Current situation",
    "Latest data",
    "Prediction markets",
    "Models and experts",
    "Key mechanisms",
    "Historical base rates",
    "Information gaps",
]
MAX_TOOL_CALLS_PER_ROUND = 3


@dataclass
class ResearchResult:
    report: str                      # final markdown, with code-generated "## Sources"
    sources: list[dict]              # [{id, title, url, published, provider, snippet}]
    window: list[str]                # [start, end] ISO
    tool_log: list[dict] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    iterations: int = 0
    summary: str = ""

    def to_dict(self) -> dict:
        return self.__dict__.copy()

    @classmethod
    def from_dict(cls, d: dict) -> "ResearchResult":
        keys = cls.__dataclass_fields__.keys()
        return cls(**{k: v for k, v in d.items() if k in keys})


class SourceRegistry:
    def __init__(self) -> None:
        self.items: list[SourceItem] = []
        self._by_url: dict[str, int] = {}

    def add(self, item: SourceItem) -> int:
        key = item.url.rstrip("/")
        if key not in self._by_url:
            self.items.append(item)
            self._by_url[key] = len(self.items)
        return self._by_url[key]

    def as_dicts(self) -> list[dict]:
        return [{"id": i + 1, **it.to_dict()} for i, it in enumerate(self.items)]


SYSTEM_PROMPT = """You are the research assistant of a team of professional forecasters.
Your job is to gather evidence, NOT to forecast. Never state your own probability or prediction
for the question. You may report probabilities published by prediction markets, models or experts,
always with their source.

Work in rounds: each round, call one or more search tools with specific, varied queries
(names, places, institutions, data series, "polymarket <topic>", "metaculus <topic>", base rates).
You must complete at least {min_it} rounds and at most {max_it} rounds of searching.

Every search result has a number like [7]. Every factual sentence in your report must cite
its source number(s) in square brackets, e.g. "Talks resumed on 3 March [2][5]." Only use
numbers you were given. If you could not find something, say so in "Information gaps".

When done, write the final report in English with EXACTLY these markdown sections, in order:
{sections}
Do not add a sources list (it is generated automatically). Do not include tool calls,
JSON, or your internal reasoning in the report."""


def _format_results(results: list[tuple[int, SourceItem]]) -> str:
    if not results:
        return "No results in the allowed time window."
    lines = []
    for n, it in results:
        date = it.published.date().isoformat() if it.published else "undated"
        lines.append(f"[{n}] {it.title} ({date}) — {it.url}\n{it.snippet.strip()[:1500]}")
    return "\n\n".join(lines)


async def run_research(ctx: RunContext, cfg: Config, qv: QuestionView) -> ResearchResult:
    r = cfg.get_path
    min_it, max_it = int(r("research.min_iterations")), int(r("research.max_iterations"))
    window = TimeWindow.for_question(cfg, ctx.cutoff, qv.resolution_date)
    tool_names = available_tools(cfg) if not ctx.fake else list(r("research.tools"))
    schemas = tool_schemas(tool_names)
    registry = SourceRegistry()

    if not schemas:
        ctx.warnings.append("No research tools available (missing API keys); research is empty.")
        empty = "\n\n".join(f"## {s}\nNo research tools were available." for s in REPORT_SECTIONS)
        return ResearchResult(report=empty, sources=[], window=[window.start.isoformat(), window.end.isoformat()],
                              warnings=list(ctx.warnings))

    system = SYSTEM_PROMPT.format(
        min_it=min_it, max_it=max_it, sections="\n".join(f"## {s}" for s in REPORT_SECTIONS)
    )
    user = (
        f"{qv.prompt_block(ctx.today)}\n\n"
        f"Search window: {window.start.date()} to {window.end.date()} (nothing after today exists for you).\n"
        "Start searching."
    )
    messages: list[dict] = [{"role": "system", "content": system}, {"role": "user", "content": user}]
    rounds = 0
    final_text = ""
    for _guard in range(max_it + 4):
        can_search = rounds < max_it
        res = await llm.complete(
            ctx, "researcher", r("models.researcher"), messages,
            temperature=r("llm.researcher_temperature", 0.2),
            tools=schemas if can_search else None,
            timeout=r("llm.timeout_seconds", 240), max_retries=r("llm.max_retries", 2),
            meta={"round": rounds, "min": min_it, "max": max_it, "question": qv},
        )
        if res.tool_calls and can_search:
            messages.append(_assistant_tool_message(res))  # clean, provider-neutral format
            for tc in res.tool_calls[:MAX_TOOL_CALLS_PER_ROUND]:
                try:
                    items = await run_tool(ctx, cfg, window, tc.name, tc.arguments)
                    numbered = [(registry.add(it), it) for it in items]
                    content = _format_results(numbered)
                except Exception as e:  # a failing tool should not kill research
                    logger.warning(f"Tool {tc.name} failed: {e}")
                    content = f"Tool error: {type(e).__name__}: {str(e)[:200]}"
                    ctx.warnings.append(f"Tool {tc.name} failed: {str(e)[:200]}")
                messages.append({"role": "tool", "tool_call_id": tc.id, "name": tc.name, "content": content})
            for tc in res.tool_calls[MAX_TOOL_CALLS_PER_ROUND:]:
                messages.append({"role": "tool", "tool_call_id": tc.id, "name": tc.name,
                                 "content": f"Skipped: max {MAX_TOOL_CALLS_PER_ROUND} searches per round."})
            rounds += 1
            if rounds >= max_it:
                messages.append({"role": "user", "content": "Search limit reached. Write the final report now."})
            continue

        if rounds < min_it:
            messages.append({"role": "assistant", "content": res.text or "(no text)"})
            messages.append({
                "role": "user",
                "content": f"You have completed {rounds} search round(s); the minimum is {min_it}. "
                           "Keep searching: cover angles you have not yet covered (base rates, prediction "
                           "markets, official statements, latest data).",
            })
            continue
        final_text = res.text
        break

    report = clean_report(final_text)
    missing = [s for s in REPORT_SECTIONS if not re.search(rf"^##\s*{re.escape(s)}", report, re.M | re.I)]
    if missing:
        # one repair attempt: same facts, correct template
        messages += [
            {"role": "assistant", "content": final_text},
            {"role": "user", "content": f"Your report is missing these sections: {missing}. Rewrite the full "
                                        f"report with exactly the required sections, keeping all citations."},
        ]
        res = await llm.complete(ctx, "researcher", r("models.researcher"), messages,
                                 temperature=0.0, timeout=r("llm.timeout_seconds", 240),
                                 meta={"repair": True, "question": qv})
        report = clean_report(res.text)
        still = [s for s in REPORT_SECTIONS if not re.search(rf"^##\s*{re.escape(s)}", report, re.M | re.I)]
        if still:
            ctx.warnings.append(f"Research report still missing sections: {still}")

    report, cited = enforce_citations(ctx, report, len(registry.items))
    sources = registry.as_dicts()
    cited_sources = [s for s in sources if s["id"] in cited]
    report += "\n\n## Sources\n" + "\n".join(
        f"[{s['id']}] {s['title']} — {s['url']}" + (f" ({s['published'][:10]})" if s["published"] else "")
        for s in cited_sources
    )
    return ResearchResult(
        report=report,
        sources=sources,
        window=[window.start.isoformat(), window.end.isoformat()],
        tool_log=list(ctx.tool_log),
        warnings=list(ctx.warnings),
        iterations=rounds,
    )


def _assistant_tool_message(res: llm.LlmResult) -> dict:
    return {
        "role": "assistant",
        "content": res.text or None,
        "tool_calls": [
            {"id": t.id, "type": "function", "function": {"name": t.name, "arguments": json.dumps(t.arguments)}}
            for t in res.tool_calls
        ],
    }


_THINK_PATTERNS = [
    r"<think(?:ing)?>.*?</think(?:ing)?>",
    r"<reasoning>.*?</reasoning>",
    r"<tool_call>.*?</tool_call>",
    r"<function_calls>.*?</function_calls>",
    r"<invoke.*?</invoke>",
    r"```(?:json|tool_code)?\s*\{\s*\"(?:name|tool|function)\".*?```",
]
_SELF_FORECAST = re.compile(
    r"[^.\n]*\b(?:I (?:would )?(?:estimate|predict|forecast|believe the probability)|my (?:forecast|estimate|prediction))\b[^.\n]*[.\n]",
    re.I,
)


def clean_report(text: str) -> str:
    out = text or ""
    for pat in _THINK_PATTERNS:
        out = re.sub(pat, "", out, flags=re.S | re.I)
    out = re.sub(r"^\s*(?:Calling|Using) tool.*$", "", out, flags=re.M | re.I)
    out = _SELF_FORECAST.sub("", out)  # the researcher must not forecast
    out = re.sub(r"^##\s*Sources\b.*", "", out, flags=re.S | re.M | re.I)  # code writes this section
    return re.sub(r"\n{3,}", "\n\n", out).strip()


def enforce_citations(ctx: RunContext, report: str, n_sources: int) -> tuple[str, set[int]]:
    """Remove citations to sources that don't exist; tag uncited factual bullets."""
    cited: set[int] = set()

    def fix(m: re.Match) -> str:
        nums = [int(x) for x in re.findall(r"\d+", m.group(0))]
        ok = [n for n in nums if 1 <= n <= n_sources]
        bad = [n for n in nums if n not in ok]
        if bad:
            ctx.warnings.append(f"Removed citation(s) to non-existent source(s) {bad}")
        cited.update(ok)
        return "".join(f"[{n}]" for n in ok)

    report = re.sub(r"\[\d+(?:\s*[,–-]\s*\d+)*\]", fix, report)
    lines = []
    section = ""
    for line in report.splitlines():
        if line.startswith("##"):
            section = line.lower()
        is_claim = line.strip().startswith(("-", "*")) or (line.strip() and not line.startswith("#"))
        if is_claim and "information gaps" not in section and not re.search(r"\[\d+\]", line) and len(line.strip()) > 25:
            line = line.rstrip() + " [unsourced]"
        lines.append(line)
    return "\n".join(lines), cited


async def summarize(ctx: RunContext, cfg: Config, qv: QuestionView, research: ResearchResult) -> str:
    """Cheaper model: two paragraphs + the source list (copied by code, not by the model)."""
    prompt = (
        f"Summarize this research in exactly two paragraphs for a forecaster working on:\n"
        f"{qv.q.question_text}\n\n"
        "Keep the [n] citations. Do not add opinions or a forecast. Do not list sources.\n\n"
        f"{research.report.split('## Sources')[0]}"
    )
    res = await llm.complete(ctx, "summarizer", cfg.get_path("models.summarizer"),
                             [{"role": "user", "content": prompt}], temperature=0.2,
                             meta={"question": qv})
    sources = research.report.split("## Sources", 1)
    return clean_report(res.text) + ("\n\n**Sources**\n" + sources[1].strip() if len(sources) > 1 else "")
